import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

const STORAGE_KEY = 'maytag-language';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.testimonials': 'Testimonials',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.wolfpack': 'Wolfpack',
    'nav.callUs': 'Call: (984) 205-9506',

    // Footer
    'footer.tagline': "Raleigh's premier coin laundry service. Clean, modern facilities with the latest equipment.",
    'footer.quickLinks': 'Quick Links',
    'footer.businessHours': 'Business Hours',
    'footer.contactUs': 'Contact Us',
    'footer.monFri': 'Mon-Fri: 6:00 AM - 10:00 PM',
    'footer.sat': 'Sat: 7:00 AM - 9:00 PM',
    'footer.sun': 'Sun: 7:00 AM - 9:00 PM',
    'footer.hours': 'Mon-Sun, 5AM to 11PM',
    'footer.aboutUs': 'About Us',
    'footer.copyright': 'Maytag Coin Laundry Raleigh. All rights reserved.',

    // Home Page - Hero
    'home.hero.title': 'Raleigh\'s Premier Laundry Service',
    'home.hero.subtitle': 'Experience the perfect combination of modern equipment, cleanliness, and convenience. Your laundry day just got easier.',
    'home.hero.contactUs': 'Contact Us',

    // Home Page - Services Section
    'home.services.title': 'Our Services',
    'home.services.subtitle': 'Whether you prefer to do it yourself or have us take care of everything, we have the perfect laundry solution for you.',
    'home.services.selfService.title': 'Self-Service Laundry',
    'home.services.selfService.description': 'Make laundry easy with high-performance Maytag washers and dryers in a variety of sizes. From small loads to comforters, we\'ve got you covered—plus free WiFi while you wait.',
    'home.services.selfService.feature1': 'High-efficiency machines',
    'home.services.selfService.feature2': 'Multiple load sizes',
    'home.services.selfService.feature3': 'Free WiFi',
    'home.services.selfService.feature4': 'Climate-controlled facility',
    
    'home.services.washFold.title': 'Wash & Fold Service',
    'home.services.washFold.description': 'Short on time? Drop off your laundry and pick it up fresh, clean, and neatly folded. Our team handles every load with care using premium detergents for results you\'ll love!',
    'home.services.washFold.feature1': 'Same-day service available',
    'home.services.washFold.feature2': 'Professional folding',
    'home.services.washFold.feature3': 'Premium detergents',
    'home.services.washFold.feature4': 'Convenient drop-off',

    'home.services.pickupDelivery.title': 'Free Pickup & Delivery',
    'home.services.pickupDelivery.description': 'Too busy to visit? We\'ll pick up your laundry and deliver it fresh and folded right to your door. Free pickup and delivery within our service area—laundry made effortless.',
    'home.services.pickupDelivery.feature1': 'Free pickup and delivery',
    'home.services.pickupDelivery.feature2': 'Same wash & fold quality',
    'home.services.pickupDelivery.feature3': 'Flexible scheduling',
    'home.services.pickupDelivery.feature4': 'Serving the Triangle area',

    // Home Page - Areas Section
    'home.areas.title': 'Areas We Serve',
    'home.areas.subtitle': "Conveniently located in Raleigh, we proudly serve customers from across the Triangle area. Whether you're from downtown or the surrounding communities, we're here to help with all your laundry needs.",
    'home.areas.serviceAreas': 'Service Areas',
    'home.areas.raleigh': 'Raleigh',
    'home.areas.raleighDesc': 'Our home base',
    'home.areas.cary': 'Cary',
    'home.areas.caryDesc': 'Quick drive west',
    'home.areas.apex': 'Apex',
    'home.areas.apexDesc': 'Southwest Triangle',
    'home.areas.eastRaleigh': 'East Raleigh',
    'home.areas.eastRaleighDesc': 'East side communities',
    'home.areas.westRaleigh': 'West Raleigh',
    'home.areas.westRaleighDesc': 'NC State area',
    'home.areas.garner': 'Garner',
    'home.areas.garnerDesc': 'South of Raleigh',
    'home.areas.visitLocation': 'Visit Our Location',
    'home.areas.businessName': 'Maytag Coin Laundry of Raleigh',
    'home.areas.servingSince': 'Serving the Triangle area since 1995',
    'home.areas.phone': 'Phone',
    'home.areas.mapHint': 'Use the map controls to zoom in and out to explore our service areas',

    // Home Page - Questions Section
    'home.questions.title': 'Have more questions?',
    'home.questions.subtitle': "Visit our store or give us a call - we're easy to reach.",
    'home.questions.findUs': 'Find us',
    'home.questions.address': '15 Jones Franklin Rd, Raleigh, NC 27606',
    'home.questions.whenOpen': "When we're open",
    'home.questions.hours': '5 AM - 11 PM, Open 7 Days Including Public Holidays',
    'home.questions.getInTouch': 'Get in touch',
    'home.questions.email': '(984) 205-9506',

    // Home Page - Testimonials
    'home.testimonials.title': 'What Our Customers Say',
    'home.testimonials.subtitle': "Don't just take our word for it. Here's what our valued customers have to say about their experience.",
    'home.testimonials.1.name': 'Sarah Johnson',
    'home.testimonials.1.text': 'The cleanest laundromat in Raleigh! The machines are always in perfect condition and the staff is incredibly helpful.',
    'home.testimonials.2.name': 'Michael Chen',
    'home.testimonials.2.text': 'I love the extended hours and free WiFi. Makes doing laundry so much more convenient. Highly recommend!',
    'home.testimonials.3.name': 'Emily Rodriguez',
    'home.testimonials.3.text': 'Great prices and excellent service. The facility is always spotless and well-maintained. My go-to laundromat.',
    'home.testimonials.4.name': 'David Thompson',
    'home.testimonials.4.text': 'Been coming here for years. Best laundromat in the area without a doubt. Always clean and machines work perfectly.',
    'home.testimonials.5.name': 'Lisa Martinez',
    'home.testimonials.5.text': 'The wash and fold service is a lifesaver! Professional, quick, and my clothes always come back perfectly folded.',
    'home.testimonials.6.name': 'James Wilson',
    'home.testimonials.6.text': 'Friendly staff, clean facility, and great prices. What more could you ask for? Highly recommend to everyone.',

    // Home Page - CTA
    'home.cta.title': 'Ready to Experience the Difference?',
    'home.cta.subtitle': "Visit us today and discover why we're Raleigh's favorite coin laundry. No appointment necessary!",
    'home.cta.button': 'Get Directions',

    // Services Page
    'services.hero.title': 'Our Services',
    'services.hero.subtitle': 'From self-service options to full-service wash and fold, we offer a complete range of laundry solutions to meet your needs.',
    'services.selfWash.title': 'Self-Service Wash',
    'services.selfWash.description': 'Use our state-of-the-art Maytag washers to clean your clothes exactly how you like them. Multiple sizes available from regular to extra-large capacity.',
    'services.selfWash.feature1': 'Regular, Large, and XL washers',
    'services.selfWash.feature2': 'Hot, warm, and cold water options',
    'services.selfWash.feature3': 'Multiple cycle settings',
    'services.selfWash.feature4': 'Energy-efficient machines',
    'services.selfDry.title': 'Self-Service Dry',
    'services.selfDry.description': 'Our high-efficiency dryers get your laundry dry quickly and evenly. Large capacity dryers can handle even your biggest loads with ease.',
    'services.selfDry.feature1': 'Multiple temperature settings',
    'services.selfDry.feature2': 'Large capacity dryers',
    'services.selfDry.feature3': 'Quick dry cycles',
    'services.selfDry.feature4': 'Wrinkle-free options',
    'services.washFold.title': 'Wash & Fold Service',
    'services.washFold.description': 'Let our professional staff handle your laundry from start to finish. Drop off your clothes and pick them up clean, fresh, and neatly folded.',
    'services.washFold.feature1': 'Same-day service available',
    'services.washFold.feature2': 'Professional folding',
    'services.washFold.feature3': 'Special care for delicates',
    'services.washFold.feature4': 'Eco-friendly detergents',
    'services.commercial.title': 'Commercial Services',
    'services.commercial.description': 'We offer bulk laundry services for businesses, hotels, and restaurants. Competitive pricing and reliable turnaround times for all your commercial needs.',
    'services.commercial.feature1': 'Bulk pricing discounts',
    'services.commercial.feature2': 'Regular pickup and delivery',
    'services.commercial.feature3': 'Customized service plans',
    'services.commercial.feature4': 'Quality guaranteed',
    'services.amenities.title': 'Premium Amenities for Your Comfort',
    'services.amenities.subtitle': "We believe doing laundry should be as comfortable and convenient as possible. That's why we've equipped our facility with modern amenities to make your visit pleasant.",
    'services.amenities.wifi': 'Free WiFi throughout facility',
    'services.amenities.seating': 'Comfortable seating areas',
    'services.amenities.vending': 'Vending machines for snacks and drinks',
    'services.amenities.folding': 'Folding tables and carts available',
    'services.amenities.atm': 'ATM on-site',
    'services.amenities.security': 'Security cameras for your safety',
    'services.amenities.parking': 'Well-lit parking area',
    'services.amenities.attendant': 'Attendant on duty during business hours',
    'services.cta.title': 'Have Questions About Our Services?',
    'services.cta.subtitle': "Our friendly staff is here to help. Visit us or give us a call to learn more about how we can make your laundry day easier.",
    'services.cta.callUs': 'Call Us Now',
    'services.cta.visitUs': 'Visit Our Location',
    'common.heroAlt': 'Maytag Coin Laundry Storefront',
    'common.imageAlt.laundromat': 'Clean, modern laundromat with Maytag equipment',

    // About Page - Additional
    'about.hero.exploreServices': 'Explore Services',
    'about.maytagStandard.title': 'The Maytag Standard',
    'about.maytagStandard.p1': "Laundry is part of everyday life, and we believe the experience should be dependable and comfortable. At Maytag Coin Laundry, we focus on providing clean machines, a modern space, and a place customers can rely on when it's time to get laundry done.",
    'about.maytagStandard.p2': "We're proud to be part of the Raleigh community. Our team takes pride in maintaining a clean laundromat and offering friendly, professional service to every customer who visits.",
    'about.equipment.sectionTitle': 'Where Service Meets Innovation',
    'about.equipment.sectionSubtitle': 'We exclusively use commercial-grade Maytag equipment, known for reliability and superior cleaning performance.',
    'about.equipment.smartLaundry.title': 'Smart Laundry Experience',
    'about.equipment.smartLaundry.desc': 'Simple digital payments, easy ordering, and a seamless system that makes doing laundry faster and more convenient every visit.',
    'about.equipment.community.title': 'Powered by Our Community',
    'about.equipment.community.desc': 'Our team comes from our community, creating a welcoming space where neighbors support neighbors and loyalty rewards give back.',
    'about.equipment.care.title': 'Care You Can See',
    'about.equipment.care.desc': 'Hands-on oversight from the owners ensures clean facilities, well-maintained machines, and a laundry experience you can rely on.',

    // Pricing Page - Washer sizes
    'pricing.washer.regular': 'Regular (20 lbs)',
    'pricing.washer.large': 'Large (40 lbs)',
    'pricing.washer.xl': 'Extra Large (60 lbs)',
    'pricing.washer.super': 'Super (80 lbs)',
    'pricing.custom': 'Custom',

    // Testimonials - Stats and Why Love (keys exist)
    // Testimonials - Individual reviews (we'll add key-based for structure)
    'testimonials.review.1.name': 'Kenneth',
    'testimonials.review.1.text': "This place is by far one of the best laundromats I've ever been. Very clean and very helpful. Me and my wife did clothes late, the owner waited til our clothes were done. I highly recommended you coming here.",
    'testimonials.review.2.name': 'Teri',
    'testimonials.review.2.text': "Nice and clean Laundromat. The machines all worked and they were clean inside and out. The place is roomy enough to sit down and rest while your clothes are getting clean. This will be the place I do laundry all the time.",
    'testimonials.review.3.name': 'Amanda',
    'testimonials.review.3.text': "My boyfriend and I love this laundry mat. We come here faithfully. We enjoy the relaxing clean quiet atmosphere.",
    'testimonials.review.4.name': 'Lorrie',
    'testimonials.review.4.text': "Great place to do your laundry. I have been twice it's clean. ALL washers and dryers are in working order. Free wifi and lots of magazines to read. Bring a book if not. Tables to sit at. Very nice.",
    'testimonials.review.5.name': 'Kasey',
    'testimonials.review.5.text': "This place is very nice, clean and has a drink machine. There is usually someone there in the next office able to help if you need it. Machines work well.",
    'testimonials.review.6.name': 'Jerome',
    'testimonials.review.6.text': "It was very clean. All equipment was very well maintained.",
    'testimonials.review.7.name': 'Mooka Moo',
    'testimonials.review.7.text': "I'm glad I went it's Great!",
    'testimonials.review.8.name': 'Local Customer',
    'testimonials.review.8.text': "Machines are clean, huge and fairly priced. Machines work great and dryers get hot!",
    'testimonials.review.9.name': 'Recent Visitor',
    'testimonials.review.9.text': "Friendly staff and there is always a person cleaning the vents to ensure machines remain operational. Great attention to maintenance.",

    // Pricing Page
    'pricing.hero.title': 'Affordable Pricing',
    'pricing.hero.subtitle': 'Transparent, competitive pricing with no hidden fees. Pay only for what you use with our flexible options.',
    'pricing.selfService.title': 'Self-Service Pricing',
    'pricing.selfService.subtitle': 'Simple, straightforward pricing for our coin-operated machines. All machines accept coins, bills, and cards.',
    'pricing.washers': 'Washers',
    'pricing.dryers': 'Dryers',
    'pricing.cycleTime': 'Cycle time',
    'pricing.per10min': 'Per 10 minutes',
    'pricing.avgCycle': 'Average full dry cycle',
    'pricing.proTip': 'Pro Tip:',
    'pricing.proTipText': 'High-efficiency dryers typically need 30-40 minutes for a full load, costing around $1.00-$2.00 total.',
    'pricing.washFold.title': 'Wash & Fold Service',
    'pricing.washFold.subtitle': "Save time with our professional wash and fold service. Drop off your laundry and we'll handle the rest.",
    'pricing.basic': 'Basic',
    'pricing.basic.desc': 'Perfect for regular laundry needs',
    'pricing.basic.feature1': 'Wash, dry, and fold',
    'pricing.basic.feature2': 'Standard detergent included',
    'pricing.basic.feature3': 'Same-day service available',
    'pricing.basic.feature4': '20 lb minimum',
    'pricing.premium': 'Premium',
    'pricing.premium.desc': 'Enhanced care for your clothes',
    'pricing.premium.feature1': 'Wash, dry, and fold',
    'pricing.premium.feature2': 'Premium eco-friendly detergent',
    'pricing.premium.feature3': 'Fabric softener included',
    'pricing.premium.feature4': 'Same-day service available',
    'pricing.premium.feature5': 'Special care for delicates',
    'pricing.premium.feature6': '15 lb minimum',
    'pricing.commercial': 'Commercial',
    'pricing.commercial.desc': 'Bulk services for businesses',
    'pricing.commercial.feature1': 'Volume discounts',
    'pricing.commercial.feature2': 'Scheduled pickup & delivery',
    'pricing.commercial.feature3': 'Dedicated account manager',
    'pricing.commercial.feature4': 'Customized service plans',
    'pricing.commercial.feature5': 'Priority processing',
    'pricing.mostPopular': 'Most Popular',
    'pricing.perLb': 'per lb',
    'pricing.customPricing': 'pricing',
    'pricing.getStarted': 'Get Started',
    'pricing.contactUs': 'Contact Us',
    'pricing.additionalServices': 'Additional Services',
    'pricing.detergent': 'Detergent',
    'pricing.detergentDesc': 'Single-use pods available',
    'pricing.fabricSoftener': 'Fabric Softener',
    'pricing.fabricSoftenerDesc': 'Dryer sheets also available',
    'pricing.stainRemover': 'Stain Remover',
    'pricing.stainRemoverDesc': 'Professional grade treatment',
    'pricing.garmentBags': 'Garment Bags',
    'pricing.garmentBagsDesc': 'Reusable mesh bags',
    'pricing.cta.title': 'Ready to Get Started?',
    'pricing.cta.subtitle': 'Visit us today or contact us to learn more about our services and pricing options.',
    'pricing.cta.visitUs': 'Visit Us Today',
    'pricing.cta.callUs': 'Call for Questions',

    // About Page
    'about.hero.title': 'About Us',
    'about.hero.subtitle': "For over 15 years, we've been Raleigh's trusted choice for quality laundry services and exceptional customer care.",
    'about.story.title': 'Our Story',
    'about.story.p1': 'Maytag Coin Laundry Raleigh was founded in 2010 with a simple mission: to provide the Raleigh community with a clean, modern, and welcoming place to do laundry. What started as a small neighborhood laundromat has grown into a full-service facility trusted by thousands of customers.',
    'about.story.p2': "We understand that doing laundry is a necessity, but that doesn't mean it has to be a chore. That's why we've invested in the best equipment, maintained the highest standards of cleanliness, and created a comfortable environment where you can get your laundry done efficiently.",
    'about.story.p3': "Over the years, we've continuously improved our services based on customer feedback, adding wash and fold services, commercial options, and modern amenities like free WiFi and comfortable seating areas. Our commitment to excellence has made us a cornerstone of the community.",
    'about.story.p4': "Today, we're proud to be locally owned and operated, serving families, students, professionals, and businesses throughout Raleigh and the surrounding areas.",
    'about.values.title': 'What We Stand For',
    'about.values.subtitle': 'Simple principles behind service you can count on.',
    'about.values.description': 'At Maytag Coin Laundry, we believe every load deserves the best. These principles drive everything we do—from our daily operations to the care we show each customer we serve.',
    'about.values.customerFirst': 'Customer First',
    'about.values.customerFirstDesc': 'Your satisfaction is our top priority. We go above and beyond to ensure every visit exceeds your expectations.',
    'about.values.quality': 'Quality Guaranteed',
    'about.values.qualityDesc': 'We keep our machines running smoothly and our space spotless for better laundry every time.',
    'about.values.professional': 'Professional Service',
    'about.values.professionalDesc': 'Our experienced staff provides knowledgeable assistance and ensures a smooth laundry experience.',
    'about.values.community': 'Community Focused',
    'about.values.communityDesc': "We’re proud to be a neighborhood laundromat serving the Raleigh community every day.",
    'about.journey.title': 'Our Journey',
    'about.journey.subtitle': "From our humble beginnings to becoming Raleigh's premier coin laundry, here are the milestones that shaped our story.",
    'about.equipment.title': 'State-of-the-Art Equipment',
    'about.equipment.subtitle': 'We exclusively use commercial-grade Maytag equipment, known for reliability and superior cleaning performance.',
    'about.equipment.washers.title': 'High-Efficiency Washers',
    'about.equipment.washers.desc': 'Our Maytag washers use less water and energy while delivering exceptional cleaning power. Multiple sizes available for any load.',
    'about.equipment.washers.feature1': 'Advanced cleaning cycles',
    'about.equipment.washers.feature2': 'Energy-efficient operation',
    'about.equipment.washers.feature3': 'Gentle on fabrics',
    'about.equipment.dryers.title': 'Commercial Dryers',
    'about.equipment.dryers.desc': 'Large-capacity dryers with precise temperature control ensure your clothes dry quickly and evenly without damage.',
    'about.equipment.dryers.feature1': 'Multiple heat settings',
    'about.equipment.dryers.feature2': 'Sensor dry technology',
    'about.equipment.dryers.feature3': 'Reduced drying time',
    'about.equipment.maintenance.title': 'Regular Maintenance',
    'about.equipment.maintenance.desc': 'All equipment is professionally maintained on a strict schedule to ensure optimal performance and reliability.',
    'about.equipment.maintenance.feature1': 'Daily cleaning protocols',
    'about.equipment.maintenance.feature2': 'Professional servicing',
    'about.equipment.maintenance.feature3': 'Immediate repairs',
    'about.cta.title': 'Experience the Difference',
    'about.cta.subtitle': 'Visit us today and discover why thousands of Raleigh residents trust us with their laundry needs.',
    'about.cta.button': 'Visit Our Location',

    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': "Have questions? We're here to help. Reach out to us and we'll respond as soon as possible.",
    'contact.address': 'Address',
    'contact.addressLine1': '15 Jones Franklin Rd',
    'contact.addressLine2': 'Raleigh, NC 27606',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.everyDay': 'Monday - Sunday',
    'contact.hoursShort': 'Mon-Fri: 5AM-11PM',
    'contact.hoursShort2': 'Sat-Sun: 7AM-9PM',
    'contact.sendMessage': 'Send Us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Best number to reach you',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'What can we help with?',
    'contact.form.selectSubject': 'Select a subject',
    'contact.form.general': 'General Inquiry',
    'contact.form.servicesQ': 'Services Question',
    'contact.form.pricingInfo': 'Pricing Information',
    'contact.form.commercialServices': 'Commercial Services',
    'contact.form.feedback': 'Feedback',
    'contact.form.namePlaceholder': 'Jane Smith',
    'contact.form.emailPlaceholder': 'jane@company.com',
    'contact.form.phonePlaceholder': '+1 (984) 205-9506',
    'contact.form.messagePlaceholder': 'Hey there, I have a quick question about...',
    'contact.form.submit': 'Submit',
    'contact.form.submitted': 'Message Sent!',
    'contact.visitLocation': 'Visit Our Location',
    'contact.businessHours': 'Business Hours',
    'contact.monFri': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.parking.title': 'Parking Information',
    'contact.parking.free': 'Free parking available in front of facility',
    'contact.parking.lit': 'Well-lit parking area for your safety',
    'contact.parking.loading': 'Easy loading and unloading access',
    'contact.parking.handicap': 'Handicap accessible spaces available',
    'contact.faq.title.line1': 'Common Questions from Our Customers',
    'contact.faq.q1': 'Do I need to bring my own detergent?',
    'contact.faq.a1': "While you're welcome to bring your own, we offer high-quality detergent, fabric softener, and other supplies for purchase on-site.",
    'contact.faq.q2': 'What payment methods do you accept?',
    'contact.faq.a2': 'We accept coins, bills, credit/debit cards, and mobile payment options. An ATM is also available on-site for your convenience.',
    'contact.faq.q3': 'Is an attendant available to help?',
    'contact.faq.a3': 'Yes! We have attendants on duty during business hours who are happy to assist you with any questions or concerns.',
    'contact.faq.q4': 'How long does a typical wash and dry take?',
    'contact.faq.a4': 'Wash cycles typically take 30-45 minutes depending on the machine size. Drying usually takes 30-40 minutes. Plan for about 60-90 minutes total.',
    'contact.cta.title': 'Still Have Questions?',
    'contact.cta.subtitle': "Give us a call or stop by during business hours. We're always happy to help!",
    'contact.cta.button': 'Call Us',

    // Testimonials Page
    'testimonials.hero.title': 'Customer Testimonials',
    'testimonials.hero.subtitle': 'See what our customers have to say about their experience at Maytag Coin Laundry. Serving Raleigh since 1995.',
    'testimonials.stats.years': 'Years of Service',
    'testimonials.stats.rating': 'Local Reputation',
    'testimonials.stats.customers': 'Customers Served',
    'testimonials.stats.machines': 'Machines Working',
    'testimonials.allReviews.title': 'What Our Customers Say',
    'testimonials.allReviews.subtitle': 'Real reviews from real customers who trust us with their laundry needs.',
    'testimonials.whyLove.title': 'Why Customers Love Us',
    'testimonials.whyLove.subtitle': 'Here are the top reasons our customers keep coming back.',
    'testimonials.whyLove.clean': 'Always Clean',
    'testimonials.whyLove.cleanDesc': 'Spotless facility and machines maintained daily',
    'testimonials.whyLove.equipment': 'Working Equipment',
    'testimonials.whyLove.equipmentDesc': 'All washers and dryers always operational',
    'testimonials.whyLove.staff': 'Friendly Staff',
    'testimonials.whyLove.staffDesc': 'Helpful team ready to assist whenever needed',
    'testimonials.whyLove.value': 'Great Value',
    'testimonials.whyLove.valueDesc': 'Fair prices for quality laundry services',
    'testimonials.cta.title': 'Ready to Experience the Difference?',
    'testimonials.cta.subtitle': 'Join thousands of satisfied customers who trust Maytag Coin Laundry for all their laundry needs.',
    'testimonials.cta.button': 'Visit Us Today',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.pricing': 'Precios',
    'nav.about': 'Nosotros',
    'nav.testimonials': 'Testimonios',
    'nav.contact': 'Contacto',
    'nav.getStarted': 'Comenzar',
    'nav.wolfpack': 'Wolfpack',
    'nav.callUs': 'Llamar: (984) 205-9506',

    // Footer
    'footer.tagline': 'El servicio de lavandería premier de Raleigh. Instalaciones limpias y modernas con el mejor equipo.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.businessHours': 'Horario de Atención',
    'footer.contactUs': 'Contáctenos',
    'footer.monFri': 'Lun-Vie: 6:00 AM - 10:00 PM',
    'footer.sat': 'Sab: 7:00 AM - 9:00 PM',
    'footer.sun': 'Dom: 7:00 AM - 9:00 PM',
    'footer.hours': 'Lun-Dom, 5AM a 11PM',
    'footer.aboutUs': 'Sobre Nosotros',
    'footer.copyright': 'Maytag Coin Laundry Raleigh. Todos los derechos reservados.',

    // Home Page - Hero
    'home.hero.title': 'El Mejor Servicio de Lavandería de Raleigh',
    'home.hero.subtitle': 'Experimente la combinación perfecta de equipo moderno, limpieza y conveniencia. Su día de lavandería ahora es más fácil.',
    'home.hero.contactUs': 'Contáctenos',

    // Home Page - Services Section
    'home.services.title': 'Nuestros Servicios',
    'home.services.subtitle': 'Ya sea que prefiera hacerlo usted mismo o que nosotros nos encarguemos de todo, tenemos la solución de lavandería perfecta para usted.',
    'home.services.selfService.title': 'Lavandería de Autoservicio',
    'home.services.selfService.description': 'Tome control de su lavandería con nuestras lavadoras y secadoras Maytag de última generación. Múltiples tamaños de máquinas disponibles para cualquier carga, desde ropa diaria hasta edredones voluminosos. Disfrute de WiFi gratis y un ambiente cómodo mientras espera.',
    'home.services.selfService.feature1': 'Máquinas de alta eficiencia',
    'home.services.selfService.feature2': 'Múltiples tamaños de carga',
    'home.services.selfService.feature3': 'WiFi gratis',
    'home.services.selfService.feature4': 'Instalacion climatizada',
    'home.services.washFold.title': 'Servicio de Lavado y Doblado',
    'home.services.washFold.description': '¿Poco tiempo? Déjenos hacer el trabajo por usted. Deje su ropa y recójala fresca, limpia y perfectamente doblada. Nuestro personal profesional trata cada artículo con cuidado usando detergentes y suavizantes premium.',
    'home.services.washFold.feature1': 'Servicio el mismo dia disponible',
    'home.services.washFold.feature2': 'Doblado profesional',
    'home.services.washFold.feature3': 'Detergentes premium',
    'home.services.washFold.feature4': 'Entrega conveniente',

    'home.services.pickupDelivery.title': 'Recogida y Entrega Gratis',
    'home.services.pickupDelivery.description': '¿Muy ocupado para visitar? Recogemos su ropa y la entregamos fresca y doblada en su puerta. Recogida y entrega gratis en nuestra área de servicio—lavandería sin esfuerzo.',
    'home.services.pickupDelivery.feature1': 'Recogida y entrega gratis',
    'home.services.pickupDelivery.feature2': 'Misma calidad de lavado y doblado',
    'home.services.pickupDelivery.feature3': 'Horarios flexibles',
    'home.services.pickupDelivery.feature4': 'Sirviendo el area del Triangulo',

    // Home Page - Areas Section
    'home.areas.title': 'Areas que Servimos',
    'home.areas.subtitle': 'Convenientemente ubicados en Raleigh, orgullosamente servimos a clientes de toda el área del Triángulo. Ya sea que venga del centro o de las comunidades cercanas, estamos aquí para ayudar con todas sus necesidades de lavandería.',
    'home.areas.serviceAreas': 'Areas de Servicio',
    'home.areas.raleigh': 'Raleigh',
    'home.areas.raleighDesc': 'Nuestra base',
    'home.areas.cary': 'Cary',
    'home.areas.caryDesc': 'Corto viaje al oeste',
    'home.areas.apex': 'Apex',
    'home.areas.apexDesc': 'Suroeste del Triángulo',
    'home.areas.eastRaleigh': 'Este de Raleigh',
    'home.areas.eastRaleighDesc': 'Comunidades del este',
    'home.areas.westRaleigh': 'Oeste de Raleigh',
    'home.areas.westRaleighDesc': 'Área de NC State',
    'home.areas.garner': 'Garner',
    'home.areas.garnerDesc': 'Sur de Raleigh',
    'home.areas.visitLocation': 'Visite Nuestra Ubicación',
    'home.areas.businessName': 'Maytag Coin Laundry de Raleigh',
    'home.areas.servingSince': 'Sirviendo el área del Triángulo desde 1995',
    'home.areas.phone': 'Teléfono',
    'home.areas.mapHint': 'Use los controles del mapa para acercar y alejar para explorar nuestras áreas de servicio',

    // Home Page - Questions Section
    'home.questions.title': '¿Tiene más preguntas?',
    'home.questions.subtitle': 'Visite nuestra tienda, llámenos o envíenos un correo electrónico; somos fáciles de contactar.',
    'home.questions.findUs': 'Encuéntrenos',
    'home.questions.address': '15 Jones Franklin Rd, Raleigh, NC 27606',
    'home.questions.whenOpen': 'Cuándo estamos abiertos',
    'home.questions.hours': '5 AM - 11 PM, Abierto 7 días incluyendo días festivos',
    'home.questions.getInTouch': 'Contáctenos',
    'home.questions.email': '(984) 205-9506',

    // Home Page - Testimonials
    'home.testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    'home.testimonials.subtitle': 'No solo tome nuestra palabra. Esto es lo que nuestros valiosos clientes dicen sobre su experiencia.',
    'home.testimonials.1.name': 'Sarah Johnson',
    'home.testimonials.1.text': '¡La lavandería más limpia de Raleigh! Las máquinas siempre están en perfectas condiciones y el personal es increíblemente servicial.',
    'home.testimonials.2.name': 'Michael Chen',
    'home.testimonials.2.text': 'Me encantan los horarios extendidos y el WiFi gratis. Hace que lavar la ropa sea mucho más conveniente. ¡Muy recomendado!',
    'home.testimonials.3.name': 'Emily Rodriguez',
    'home.testimonials.3.text': 'Excelentes precios y servicio. Las instalaciones siempre están impecables y bien mantenidas. Mi lavandería favorita.',
    'home.testimonials.4.name': 'David Thompson',
    'home.testimonials.4.text': 'Vengo aquí desde hace años. Sin duda la mejor lavandería de la zona. Siempre limpia y las máquinas funcionan perfectamente.',
    'home.testimonials.5.name': 'Lisa Martinez',
    'home.testimonials.5.text': '¡El servicio de lavado y doblado es un salvavidas! Profesional, rápido y mi ropa siempre vuelve perfectamente doblada.',
    'home.testimonials.6.name': 'James Wilson',
    'home.testimonials.6.text': 'Personal amable, instalaciones limpias y excelentes precios. ¿Qué más se puede pedir? Muy recomendado para todos.',

    // Home Page - CTA
    'home.cta.title': '¿Listo para Experimentar la Diferencia?',
    'home.cta.subtitle': 'Visítenos hoy y descubra por qué somos la lavandería favorita de Raleigh. ¡No necesita cita!',
    'home.cta.button': 'Obtener Direcciones',

    // Services Page
    'services.hero.title': 'Nuestros Servicios',
    'services.hero.subtitle': 'Desde opciones de autoservicio hasta servicio completo de lavado y doblado, ofrecemos una gama completa de soluciones de lavandería para satisfacer sus necesidades.',
    'services.selfWash.title': 'Lavado de Autoservicio',
    'services.selfWash.description': 'Use nuestras lavadoras Maytag de última generación para limpiar su ropa exactamente como le gusta. Múltiples tamaños disponibles desde capacidad regular hasta extra grande.',
    'services.selfWash.feature1': 'Lavadoras regulares, grandes y XL',
    'services.selfWash.feature2': 'Opciones de agua caliente, tibia y fria',
    'services.selfWash.feature3': 'Multiples configuraciones de ciclo',
    'services.selfWash.feature4': 'Máquinas de bajo consumo',
    'services.selfDry.title': 'Secado de Autoservicio',
    'services.selfDry.description': 'Nuestras secadoras de alta eficiencia secan su ropa rápida y uniformemente. Las secadoras de gran capacidad pueden manejar incluso sus cargas más grandes con facilidad.',
    'services.selfDry.feature1': 'Multiples configuraciones de temperatura',
    'services.selfDry.feature2': 'Secadoras de gran capacidad',
    'services.selfDry.feature3': 'Ciclos de secado rápido',
    'services.selfDry.feature4': 'Opciones sin arrugas',
    'services.washFold.title': 'Servicio de Lavado y Doblado',
    'services.washFold.description': 'Deje que nuestro personal profesional maneje su ropa de principio a fin. Deje su ropa y recojala limpia, fresca y perfectamente doblada.',
    'services.washFold.feature1': 'Servicio el mismo dia disponible',
    'services.washFold.feature2': 'Doblado profesional',
    'services.washFold.feature3': 'Cuidado especial para prendas delicadas',
    'services.washFold.feature4': 'Detergentes ecológicos',
    'services.commercial.title': 'Servicios Comerciales',
    'services.commercial.description': 'Ofrecemos servicios de lavandería al por mayor para negocios, hoteles y restaurantes. Precios competitivos y tiempos de entrega confiables para todas sus necesidades comerciales.',
    'services.commercial.feature1': 'Descuentos por volumen',
    'services.commercial.feature2': 'Recogida y entrega regular',
    'services.commercial.feature3': 'Planes de servicio personalizados',
    'services.commercial.feature4': 'Calidad garantizada',
    'services.amenities.title': 'Comodidades Premium para Su Confort',
    'services.amenities.subtitle': 'Creemos que hacer la lavandería debe ser lo más cómodo y conveniente posible. Por eso hemos equipado nuestras instalaciones con comodidades modernas para hacer su visita agradable.',
    'services.amenities.wifi': 'WiFi gratis en toda la instalacion',
    'services.amenities.seating': 'Áreas de asientos cómodas',
    'services.amenities.vending': 'Máquinas expendedoras de snacks y bebidas',
    'services.amenities.folding': 'Mesas de doblado y carritos disponibles',
    'services.amenities.atm': 'Cajero automatico en el lugar',
    'services.amenities.security': 'Cámaras de seguridad para su protección',
    'services.amenities.parking': 'Area de estacionamiento bien iluminada',
    'services.amenities.attendant': 'Personal de servicio durante horas de operación',
    'services.cta.title': '¿Tiene Preguntas Sobre Nuestros Servicios?',
    'services.cta.subtitle': 'Nuestro amable personal está aquí para ayudar. Visítenos o llámenos para saber más sobre cómo podemos hacer su día de lavandería más fácil.',
    'services.cta.callUs': 'Llámennos Ahora',
    'services.cta.visitUs': 'Visite Nuestra Ubicación',
    'common.heroAlt': 'Fachada de Maytag Coin Laundry',
    'common.imageAlt.laundromat': 'Lavandería limpia y moderna con equipo Maytag',

    // About Page - Additional
    'about.hero.exploreServices': 'Explorar Servicios',
    'about.maytagStandard.title': 'El Estándar Maytag',
    'about.maytagStandard.p1': 'La lavandería es parte de la vida cotidiana, y creemos que la experiencia debe ser confiable y cómoda. En Maytag Coin Laundry, nos enfocamos en proporcionar máquinas limpias, un espacio moderno y un lugar en el que los clientes puedan confiar cuando llega el momento de lavar.',
    'about.maytagStandard.p2': 'Estamos orgullosos de ser parte de la comunidad de Raleigh. Nuestro equipo se enorgullece de mantener una lavandería limpia y ofrecer un servicio amable y profesional a cada cliente que nos visita.',
    'about.equipment.sectionTitle': 'Donde el Servicio Encuentra la Innovación',
    'about.equipment.sectionSubtitle': 'Utilizamos exclusivamente equipo Maytag de grado comercial, conocido por su confiabilidad y rendimiento de limpieza superior.',
    'about.equipment.smartLaundry.title': 'Experiencia de Lavandería Inteligente',
    'about.equipment.smartLaundry.desc': 'Pagos digitales simples, pedidos fáciles y un sistema fluido que hace que lavar la ropa sea más rápido y conveniente en cada visita.',
    'about.equipment.community.title': 'Impulsados por Nuestra Comunidad',
    'about.equipment.community.desc': 'Nuestro equipo proviene de nuestra comunidad, creando un espacio acogedor donde los vecinos se apoyan entre sí y las recompensas de lealtad retribuyen.',
    'about.equipment.care.title': 'Atención que Puede Ver',
    'about.equipment.care.desc': 'La supervisión directa de los propietarios garantiza instalaciones limpias, máquinas bien mantenidas y una experiencia de lavandería en la que puede confiar.',

    // Pricing Page - Washer sizes
    'pricing.washer.regular': 'Regular (20 lbs)',
    'pricing.washer.large': 'Grande (40 lbs)',
    'pricing.washer.xl': 'Extra Grande (60 lbs)',
    'pricing.washer.super': 'Súper (80 lbs)',
    'pricing.custom': 'Personalizado',

    // Testimonials - Individual reviews (Spanish translations)
    'testimonials.review.1.name': 'Kenneth',
    'testimonials.review.1.text': "Este lugar es, sin duda, una de las mejores lavanderías en las que he estado. Muy limpio y muy servicial. Mi esposa y yo lavamos tarde y el dueño esperó hasta que terminamos. Les recomiendo mucho que vengan aquí.",
    'testimonials.review.2.name': 'Teri',
    'testimonials.review.2.text': "Lavandería agradable y limpia. Todas las máquinas funcionaban y estaban limpias por dentro y por fuera. El lugar es lo suficientemente amplio para sentarse y descansar mientras la ropa se lava. Este será el lugar donde lavaré la ropa siempre.",
    'testimonials.review.3.name': 'Amanda',
    'testimonials.review.3.text': "Mi novio y yo amamos esta lavandería. Venimos fielmente. Disfrutamos del ambiente relajado, limpio y tranquilo.",
    'testimonials.review.4.name': 'Lorrie',
    'testimonials.review.4.text': "Excelente lugar para lavar la ropa. He venido dos veces y está limpio. Todas las lavadoras y secadoras funcionan. WiFi gratis y muchas revistas para leer. Traiga un libro si no. Mesas para sentarse. Muy agradable.",
    'testimonials.review.5.name': 'Kasey',
    'testimonials.review.5.text': "Este lugar es muy agradable, limpio y tiene una máquina de bebidas. Generalmente hay alguien en la oficina de al lado que puede ayudar si lo necesita. Las máquinas funcionan bien.",
    'testimonials.review.6.name': 'Jerome',
    'testimonials.review.6.text': "Estaba muy limpio. Todo el equipo estaba muy bien mantenido.",
    'testimonials.review.7.name': 'Mooka Moo',
    'testimonials.review.7.text': "¡Me alegra haber venido, es genial!",
    'testimonials.review.8.name': 'Cliente Local',
    'testimonials.review.8.text': "Las máquinas están limpias, son enormes y tienen precios justos. Las máquinas funcionan muy bien y las secadoras se calientan mucho.",
    'testimonials.review.9.name': 'Visitante Reciente',
    'testimonials.review.9.text': "Personal amable y siempre hay alguien limpiando las rejillas para asegurar que las máquinas sigan funcionando. Gran atención al mantenimiento.",

    // Pricing Page
    'pricing.hero.title': 'Precios Accesibles',
    'pricing.hero.subtitle': 'Precios transparentes y competitivos sin cargos ocultos. Pague solo por lo que use con nuestras opciones flexibles.',
    'pricing.selfService.title': 'Precios de Autoservicio',
    'pricing.selfService.subtitle': 'Precios simples y directos para nuestras máquinas operadas con monedas. Todas las máquinas aceptan monedas, billetes y tarjetas.',
    'pricing.washers': 'Lavadoras',
    'pricing.dryers': 'Secadoras',
    'pricing.cycleTime': 'Tiempo de ciclo',
    'pricing.per10min': 'Por 10 minutos',
    'pricing.avgCycle': 'Ciclo completo promedio',
    'pricing.proTip': 'Consejo:',
    'pricing.proTipText': 'Las secadoras de alta eficiencia típicamente necesitan 30-40 minutos para una carga completa, costando alrededor de $1.00-$2.00 en total.',
    'pricing.washFold.title': 'Servicio de Lavado y Doblado',
    'pricing.washFold.subtitle': 'Ahorre tiempo con nuestro servicio profesional de lavado y doblado. Deje su ropa y nosotros nos encargamos del resto.',
    'pricing.basic': 'Basico',
    'pricing.basic.desc': 'Perfecto para necesidades regulares de lavanderia',
    'pricing.basic.feature1': 'Lavar, secar y doblar',
    'pricing.basic.feature2': 'Detergente estandar incluido',
    'pricing.basic.feature3': 'Servicio el mismo dia disponible',
    'pricing.basic.feature4': 'Minimo 20 lbs',
    'pricing.premium': 'Premium',
    'pricing.premium.desc': 'Cuidado mejorado para su ropa',
    'pricing.premium.feature1': 'Lavar, secar y doblar',
    'pricing.premium.feature2': 'Detergente premium ecologico',
    'pricing.premium.feature3': 'Suavizante incluido',
    'pricing.premium.feature4': 'Servicio el mismo dia disponible',
    'pricing.premium.feature5': 'Cuidado especial para delicados',
    'pricing.premium.feature6': 'Minimo 15 lbs',
    'pricing.commercial': 'Comercial',
    'pricing.commercial.desc': 'Servicios al por mayor para negocios',
    'pricing.commercial.feature1': 'Descuentos por volumen',
    'pricing.commercial.feature2': 'Recogida y entrega programada',
    'pricing.commercial.feature3': 'Gerente de cuenta dedicado',
    'pricing.commercial.feature4': 'Planes de servicio personalizados',
    'pricing.commercial.feature5': 'Procesamiento prioritario',
    'pricing.mostPopular': 'Mas Popular',
    'pricing.perLb': 'por lb',
    'pricing.customPricing': 'precios',
    'pricing.getStarted': 'Comenzar',
    'pricing.contactUs': 'Contactenos',
    'pricing.additionalServices': 'Servicios Adicionales',
    'pricing.detergent': 'Detergente',
    'pricing.detergentDesc': 'Capsulas de un solo uso disponibles',
    'pricing.fabricSoftener': 'Suavizante',
    'pricing.fabricSoftenerDesc': 'Hojas de secadora tambien disponibles',
    'pricing.stainRemover': 'Quitamanchas',
    'pricing.stainRemoverDesc': 'Tratamiento de grado profesional',
    'pricing.garmentBags': 'Bolsas de Ropa',
    'pricing.garmentBagsDesc': 'Bolsas de malla reutilizables',
    'pricing.cta.title': 'Listo para Comenzar?',
    'pricing.cta.subtitle': 'Visitenos hoy o contactenos para saber mas sobre nuestros servicios y opciones de precios.',
    'pricing.cta.visitUs': 'Visitenos Hoy',
    'pricing.cta.callUs': 'Llame para Preguntas',

    // About Page
    'about.hero.title': 'Sobre Nosotros',
    'about.hero.subtitle': 'Por mas de 15 anos, hemos sido la opcion de confianza de Raleigh para servicios de lavanderia de calidad y atencion al cliente excepcional.',
    'about.story.title': 'Nuestra Historia',
    'about.story.p1': 'Maytag Coin Laundry Raleigh fue fundada en 2010 con una mision simple: proporcionar a la comunidad de Raleigh un lugar limpio, moderno y acogedor para hacer la lavanderia. Lo que comenzo como una pequena lavanderia de barrio ha crecido hasta convertirse en una instalacion de servicio completo en la que confian miles de clientes.',
    'about.story.p2': 'Entendemos que hacer la lavanderia es una necesidad, pero eso no significa que tenga que ser una tarea pesada. Por eso hemos invertido en el mejor equipo, mantenido los mas altos estandares de limpieza y creado un ambiente comodo donde puede hacer su lavanderia de manera eficiente.',
    'about.story.p3': 'A lo largo de los anos, hemos mejorado continuamente nuestros servicios basandonos en los comentarios de los clientes, agregando servicios de lavado y doblado, opciones comerciales y comodidades modernas como WiFi gratis y areas de asientos comodas. Nuestro compromiso con la excelencia nos ha convertido en un pilar de la comunidad.',
    'about.story.p4': 'Hoy, estamos orgullosos de ser de propiedad local y operados localmente, sirviendo a familias, estudiantes, profesionales y negocios en todo Raleigh y las areas circundantes.',
    'about.values.title': 'Nuestros Valores',
    'about.values.subtitle': 'Estos valores fundamentales guian todo lo que hacemos y dan forma a la experiencia que brindamos a nuestros clientes.',
    'about.values.description': 'En Maytag Coin Laundry, creemos que cada carga merece lo mejor. Estos principios impulsan todo lo que hacemos—desde nuestras operaciones diarias hasta la atención que brindamos a cada cliente que atendemos.',
    'about.values.customerFirst': 'Cliente Primero',
    'about.values.customerFirstDesc': 'Su satisfaccion es nuestra maxima prioridad. Hacemos todo lo posible para garantizar que cada visita supere sus expectativas.',
    'about.values.quality': 'Calidad Garantizada',
    'about.values.qualityDesc': 'Mantenemos los mas altos estandares en mantenimiento de equipos y limpieza de instalaciones para los mejores resultados.',
    'about.values.professional': 'Servicio Profesional',
    'about.values.professionalDesc': 'Nuestro personal experimentado brinda asistencia conocedora y garantiza una experiencia de lavanderia sin problemas.',
    'about.values.community': 'Enfocados en la Comunidad',
    'about.values.communityDesc': 'Como negocio local, estamos comprometidos a servir y apoyar a la comunidad de Raleigh.',
    'about.journey.title': 'Nuestro Recorrido',
    'about.journey.subtitle': 'Desde nuestros humildes comienzos hasta convertirnos en la lavanderia premier de Raleigh, estos son los hitos que dieron forma a nuestra historia.',
    'about.equipment.title': 'Equipo de Ultima Generacion',
    'about.equipment.subtitle': 'Utilizamos exclusivamente equipos Maytag de grado comercial, conocidos por su confiabilidad y rendimiento de limpieza superior.',
    'about.equipment.washers.title': 'Lavadoras de Alta Eficiencia',
    'about.equipment.washers.desc': 'Nuestras lavadoras Maytag usan menos agua y energia mientras ofrecen un poder de limpieza excepcional. Multiples tamanos disponibles para cualquier carga.',
    'about.equipment.washers.feature1': 'Ciclos de limpieza avanzados',
    'about.equipment.washers.feature2': 'Operacion de bajo consumo',
    'about.equipment.washers.feature3': 'Suave con las telas',
    'about.equipment.dryers.title': 'Secadoras Comerciales',
    'about.equipment.dryers.desc': 'Secadoras de gran capacidad con control de temperatura preciso aseguran que su ropa se seque rapida y uniformemente sin danos.',
    'about.equipment.dryers.feature1': 'Multiples configuraciones de calor',
    'about.equipment.dryers.feature2': 'Tecnologia de secado con sensor',
    'about.equipment.dryers.feature3': 'Tiempo de secado reducido',
    'about.equipment.maintenance.title': 'Mantenimiento Regular',
    'about.equipment.maintenance.desc': 'Todo el equipo recibe mantenimiento profesional en un horario estricto para garantizar un rendimiento y confiabilidad optimos.',
    'about.equipment.maintenance.feature1': 'Protocolos de limpieza diarios',
    'about.equipment.maintenance.feature2': 'Servicio profesional',
    'about.equipment.maintenance.feature3': 'Reparaciones inmediatas',
    'about.cta.title': 'Experimente la Diferencia',
    'about.cta.subtitle': 'Visitenos hoy y descubra por que miles de residentes de Raleigh nos confian sus necesidades de lavanderia.',
    'about.cta.button': 'Visite Nuestra Ubicación',

    // Contact Page
    'contact.hero.title': 'Contactenos',
    'contact.hero.subtitle': 'Tiene preguntas? Estamos aqui para ayudar. Comuniquese con nosotros y le responderemos lo antes posible.',
    'contact.address': 'Dirección',
    'contact.addressLine1': '15 Jones Franklin Rd',
    'contact.addressLine2': 'Raleigh, NC 27606',
    'contact.phone': 'Teléfono',
    'contact.email': 'Correo',
    'contact.hours': 'Horario',
    'contact.everyDay': 'Lunes - Domingo',
    'contact.hoursShort': 'Lun-Vie: 5AM-11PM',
    'contact.hoursShort2': 'Sab-Dom: 7AM-9PM',
    'contact.sendMessage': 'Envienos un Mensaje',
    'contact.form.name': 'Su nombre',
    'contact.form.email': 'Correo electrónico',
    'contact.form.phone': 'Mejor número para contactarle',
    'contact.form.subject': 'Asunto',
    'contact.form.message': '¿En qué podemos ayudarle?',
    'contact.form.selectSubject': 'Seleccione un asunto',
    'contact.form.general': 'Consulta General',
    'contact.form.servicesQ': 'Pregunta de Servicios',
    'contact.form.pricingInfo': 'Informacion de Precios',
    'contact.form.commercialServices': 'Servicios Comerciales',
    'contact.form.feedback': 'Comentarios',
    'contact.form.namePlaceholder': 'María García',
    'contact.form.emailPlaceholder': 'maria@empresa.com',
    'contact.form.phonePlaceholder': '+1 (984) 205-9506',
    'contact.form.messagePlaceholder': 'Hola, tengo una pregunta rápida sobre...',
    'contact.form.submit': 'Enviar',
    'contact.form.submitted': 'Mensaje Enviado!',
    'contact.visitLocation': 'Visite Nuestra Ubicación',
    'contact.businessHours': 'Horario de Atencion',
    'contact.monFri': 'Lunes - Viernes',
    'contact.saturday': 'Sabado',
    'contact.sunday': 'Domingo',
    'contact.parking.title': 'Informacion de Estacionamiento',
    'contact.parking.free': 'Estacionamiento gratis disponible frente a la instalacion',
    'contact.parking.lit': 'Area de estacionamiento bien iluminada para su seguridad',
    'contact.parking.loading': 'Facil acceso para carga y descarga',
    'contact.parking.handicap': 'Espacios accesibles para discapacitados disponibles',
    'contact.faq.title.line1': 'Preguntas frecuentes de nuestros clientes',
    'contact.faq.title.line2': 'Estamos aquí para ayudar',
    'contact.faq.q1': 'Necesito traer mi propio detergente?',
    'contact.faq.a1': 'Aunque puede traer el suyo, ofrecemos detergente de alta calidad, suavizante y otros suministros para comprar en el lugar.',
    'contact.faq.q2': 'Que metodos de pago aceptan?',
    'contact.faq.a2': 'Aceptamos monedas, billetes, tarjetas de credito/debito y opciones de pago movil. Tambien hay un cajero automatico disponible en el lugar.',
    'contact.faq.q3': 'Hay personal disponible para ayudar?',
    'contact.faq.a3': 'Si! Tenemos personal de servicio durante las horas de operacion que estara encantado de ayudarle con cualquier pregunta o inquietud.',
    'contact.faq.q4': 'Cuanto tiempo toma un lavado y secado tipico?',
    'contact.faq.a4': 'Los ciclos de lavado tipicamente toman 30-45 minutos dependiendo del tamano de la maquina. El secado usualmente toma 30-40 minutos. Planee aproximadamente 60-90 minutos en total.',
    'contact.cta.title': 'Todavia Tiene Preguntas?',
    'contact.cta.subtitle': 'Llamenos o visitenos durante las horas de operacion. Siempre estaremos encantados de ayudar!',
    'contact.cta.button': 'Llamenos',

    // Testimonials Page
    'testimonials.hero.title': 'Testimonios de Clientes',
    'testimonials.hero.subtitle': 'Vea lo que nuestros clientes dicen sobre su experiencia en Maytag Coin Laundry. Sirviendo a Raleigh desde 1995.',
    'testimonials.stats.years': 'Anos de Servicio',
    'testimonials.stats.rating': 'Calificacion Promedio',
    'testimonials.stats.customers': 'Clientes Felices',
    'testimonials.stats.machines': 'Maquinas Funcionando',
    'testimonials.allReviews.title': 'Lo Que Dicen Nuestros Clientes',
    'testimonials.allReviews.subtitle': 'Resenas reales de clientes reales que nos confian sus necesidades de lavanderia.',
    'testimonials.whyLove.title': 'Por Que Nos Aman los Clientes',
    'testimonials.whyLove.subtitle': 'Estas son las principales razones por las que nuestros clientes siguen regresando.',
    'testimonials.whyLove.clean': 'Siempre Limpio',
    'testimonials.whyLove.cleanDesc': 'Instalaciones impecables y maquinas mantenidas diariamente',
    'testimonials.whyLove.equipment': 'Equipo Funcionando',
    'testimonials.whyLove.equipmentDesc': 'Todas las lavadoras y secadoras siempre operativas',
    'testimonials.whyLove.staff': 'Personal Amable',
    'testimonials.whyLove.staffDesc': 'Equipo servicial listo para ayudar cuando lo necesite',
    'testimonials.whyLove.value': 'Gran Valor',
    'testimonials.whyLove.valueDesc': 'Precios justos para servicios de lavanderia de calidad',
    'testimonials.cta.title': 'Listo para Experimentar la Diferencia?',
    'testimonials.cta.subtitle': 'Unase a miles de clientes satisfechos que confian en Maytag Coin Laundry para todas sus necesidades de lavanderia.',
    'testimonials.cta.button': 'Visitenos Hoy',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
      if (stored === 'en' || stored === 'es') return stored;
    }
    return 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, language);
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
